SELECT DEPT_NAME , COUNT(*) FROM STUDENT JOIN DEPARTMENT ON DEPT_ID = DEPARTMENT_ID  GROUP BY DEPARTMENT_ID ORDER BY DEPT_NAME DESC;

SELECT DEPT_NAME,FACULTY_NAME AS DEPT_MANAGER_NAME 
FROM FACULTY 
JOIN DEPARTMENT ON MGR_ID = FACULTY_ID;


CREATE VIEW VW AS (
SELECT DEPT_NAME,COUNT(*) AS COURSE_COUNT FROM DEPARTMENT AS D,COURSE AS C 
WHERE
 D.DEPARTMENT_ID = C.DEPT_ID GROUP BY DEPT_NAME
)
;

SELECT DEPT_NAME,COURSE_COUNT AS MAX_COURSE_COUNT 
FROM VW 
WHERE COURSE_COUNT IN (
SELECT MAX(COURSE_COUNT) FROM VW
     )
;


SELECT STUDENT.* 
FROM STUDENT 
WHERE SRN IN
(
SELECT S.SRN FROM STUDENT AS S 
EXCEPT 
SELECT SH.SRN FROM STUD_HOSTEL AS SH
)
;


SELECT STUDENT.* 
FROM STUDENT
 LEFT OUTER JOIN STUD_HOSTEL ON STUDENT.SRN = STUD_HOSTEL.SRN 
WHERE STUD_HOSTEL.SRN IS NULL; 

SELECT * 
FROM STUDENT 
WHERE SRN IN
 (
SELECT SRN FROM EXAM_STUD WHERE EM_ID IN 
(
SELECT EXAM_ID FROM EXAM WHERE CRS_ID IN 
(
SELECT COURSE_ID FROM COURSE WHERE COURSE_NAME IN ('DATA SCIENCE')
)
) AND GRADE='F'
)
;

SELECT STUDENT.* 
FROM EXAM_STUD,EXAM,COURSE,STUDENT 
WHERE EM_ID = EXAM_ID AND CRS_ID = COURSE_ID AND EXAM_STUD.SRN = STUDENT.SRN AND COURSE_NAME = 'DATA SCIENCE' AND GRADE = 'F';



SELECT SECTION,AVG(MARKS) AS AVG_SECTION_MARKS 
FROM EXAM_STUD AS ES,EXAM,COURSE,STUDENT AS S 
WHERE EXAM_ID = EM_ID AND S.SRN = ES.SRN AND CRS_ID = COURSE_ID AND COURSE_NAME='DATA SCIENCE' 
GROUP BY SECTION;


SELECT BOOK.* 
FROM 
(
(
BOOK_STUD JOIN BOOK ON BOOK_STUD.ISBN = BOOK.ISBN AND BOOK_STUD.COPY_NO = BOOK.COPY_NO
)
 JOIN 
STUDENT ON BOOK_STUD.SRN = STUDENT.SRN AND STUDENT.SRN = 'ABC4567898'
)
;


SELECT DISTINCT ISBN,BOOK_NAME,AUTHOR,PUBLISHER FROM BOOK WHERE ISBN IN (
SELECT ISBN  FROM BOOK_STUD WHERE SRN IN ('ABC4567898')
);



SELECT E.SRN,AVG(E.MARKS)
FROM EXAM_STUD AS E,STUDENT AS S
WHERE S.SRN=E.SRN AND S.STUD_NAME='ADARSH'
GROUP BY E.SRN;


SELECT * 
FROM STUDENT AS S
WHERE S.SRN IN
(
SELECT E.SRN
FROM STUDENT AS S,EXAM_STUD AS E
WHERE E.SRN=S.SRN
GROUP BY E.SRN
HAVING AVG(E.MARKS)>70
)
;


SELECT SRN
FROM EXAM_STUD 
NATURAL JOIN STUDENT
GROUP BY SRN 
HAVING AVG(MARKS) > 70;


SELECT FACULTY.* 
FROM FACULTY_COURSE,COURSE,FACULTY 
WHERE 
COURSE_ID = CRS_ID 
AND FAC_RATING < '5' 
AND FACULTY_ID = FAC_ID 
AND COURSE_NAME ='DATA SCIENCE' ;

SELECT FACULTY.* 
FROM FACULTY 
WHERE
 FACULTY_ID IN (
SELECT FAC_ID FROM FACULTY_COURSE WHERE CRS_ID IN (
SELECT COURSE_ID FROM COURSE WHERE COURSE_NAME IN ('DATA SCIENCE') AND FAC_RATING < '5'						   )
)
;


